[package]
name = "blog_files_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
glob = "0.3.1"
syn = "2.0.47"
quote = "1.0.35"

